import tkinter
from tkinter import *
win = Tk()
def add(): lblResult.config(text="Results: " + str(float(txt1.get()) + float(txt2.get())))
def subtract(): lblResult.config(text="Results: " + str(float(txt1.get()) - float(txt2.get())))
def multiply(): lblResult.config(text="Results: " + str(float(txt1.get()) * float(txt2.get())))
def divide(): lblResult.config(text="Results: " + str(float(txt1.get()) / float(txt2.get())))
def floordiv(): lblResult.config(text="Results: " + str(int(txt1.get()) // int(txt2.get())))
def exponent(): lblResult.config(text="Results: " + str(float(txt1.get()) ** float(txt2.get())))
def modulus(): lblResult.config(text="Results: " + str(int(txt1.get()) % int(txt2.get())))   
lblTitle1 = Label (win, text="Python GUI: Calculator", bg= "#F4F6FF",font= ("Century Gothic", 15))
lblTitle1.place(x= 255, y=15)
lblTitle1 = Label (win, text="First Number:", bg= "#F4F6FF",font= ("Century Gothic", 15))
lblTitle1.place(x= 20, y=100)
txt1 = Entry(win, width= 27, font= ("Century Gothic", 15))
txt1.place(x=220, y=100)
lblTitle2 = Label(win, text = " Second Number:", bg= "#F4F6FF",font= ("Century Gothic", 15))
lblTitle2.place(x= 13, y=150)
txt2 = Entry(win, width= 27, font= ("Century Gothic", 15))
txt2.place(x=220, y=150)
lblResult = Label(win, text = " Results: ", bg= "#F4F6FF",font= ("Century Gothic", 15))
lblResult.place(x= 20, y=200)
btn1 = Button(win, height= 2, width= 7, text= "+", font= ("Century Gothic", 12), bg= "#c0d6e4", command = add)
btn1.place(x=50, y=400)
btn2 = Button(win,  height= 2, width= 7, text= "-", font= ("Century Gothic", 12), bg= "#c0d6e4", command = subtract)
btn2.place(x=140, y=400)
btn3 = Button(win,  height= 2, width= 7, text= "*", font= ("Century Gothic", 12), bg= "#c0d6e4", command = multiply)
btn3.place(x=230, y=400)
btn4 = Button(win,  height= 2, width= 7, text= "÷", font= ("Century Gothic", 12), bg= "#c0d6e4", command = divide)
btn4.place(x=320, y=400)
btn5 = Button(win,  height= 2, width= 7, text= "//", font= ("Century Gothic", 12), bg= "#c0d6e4", command = floordiv)
btn5.place(x=410, y=400)
btn6 = Button(win,  height= 2, width= 7, text= "^", font= ("Century Gothic", 12), bg= "#c0d6e4", command = exponent)
btn6.place(x=500, y=400)
btn7 = Button(win,  height= 2, width= 7, text= "%", font= ("Century Gothic", 12), bg= "#c0d6e4", command = modulus)
btn7.place(x=590, y=400)
win.title("Python GUI: Calculator:")
win.config(bg= "#F4F6FF")
win.geometry("700x500+650+280")
win.mainloop()
